let data = [
  {
    availabilityStatus: 'In Stock',
    brand: 'Nail Couture',
    category: 'beauty',
    description:
      'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
    dimensions: {depth: 29.06, height: 10.89, width: 8.11},
    discountPercentage: 2.46,
    id: 5,
    images: [
      'https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/1.png',
    ],
    meta: {
      barcode: '3212847902461',
      createdAt: '2024-05-23T08:56:21.619Z',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
      updatedAt: '2024-05-23T08:56:21.619Z',
    },
    minimumOrderQuantity: 46,
    price: 8.99,
    quantity: 2,
    rating: 3.91,
    returnPolicy: 'No return policy',
    reviews: [[Object], [Object], [Object]],
    shippingInformation: 'Ships in 1 week',
    sku: 'YUIIIP4W',
    stock: 71,
    tags: ['beauty', 'nail polish'],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png',
    title: 'Red Nail Polish',
    warrantyInformation: '1 year warranty',
    weight: 9,
  },
  {
    availabilityStatus: 'In Stock',
    brand: 'Calvin Klein',
    category: 'fragrances',
    description:
      "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
    dimensions: {depth: 6.81, height: 14.44, width: 11.53},
    discountPercentage: 0.32,
    id: 6,
    images: [
      'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/1.png',
      'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/2.png',
      'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/3.png',
    ],
    meta: {
      barcode: '2210136215089',
      createdAt: '2024-05-23T08:56:21.619Z',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
      updatedAt: '2024-05-23T08:56:21.619Z',
    },
    minimumOrderQuantity: 20,
    price: 49.99,
    quantity: 1,
    rating: 4.85,
    returnPolicy: 'No return policy',
    reviews: [[Object], [Object], [Object]],
    shippingInformation: 'Ships overnight',
    sku: 'DZM2JQZE',
    stock: 17,
    tags: ['fragrances', 'perfumes'],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png',
    title: 'Calvin Klein CK One',
    warrantyInformation: '5 year warranty',
    weight: 5,
  },
  {
    availabilityStatus: 'In Stock',
    brand: 'Chanel',
    category: 'fragrances',
    description:
      'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
    dimensions: {depth: 11.89, height: 28, width: 21.27},
    discountPercentage: 18.64,
    id: 7,
    images: [
      'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/1.png',
      'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/2.png',
      'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/3.png',
    ],
    meta: {
      barcode: '1435582999795',
      createdAt: '2024-05-23T08:56:21.619Z',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
      updatedAt: '2024-05-23T08:56:21.619Z',
    },
    minimumOrderQuantity: 5,
    price: 129.99,
    quantity: 1,
    rating: 2.76,
    returnPolicy: '60 days return policy',
    reviews: [[Object], [Object], [Object]],
    shippingInformation: 'Ships in 1 month',
    sku: 'K71HBCGS',
    stock: 41,
    tags: ['fragrances', 'perfumes'],
    thumbnail:
      'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png',
    title: 'Chanel Coco Noir Eau De',
    warrantyInformation: '1 week warranty',
    weight: 4,
  },
  {
    availabilityStatus: 'In Stock',
    brand: 'Dior',
    category: 'fragrances',
    description:
      "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
    dimensions: {depth: 26.51, height: 7, width: 21.51},
    discountPercentage: 17.44,
    id: 8,
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/3.png",
    ],
    meta: {
      barcode: '0887083199279',
      createdAt: '2024-05-23T08:56:21.619Z',
      qrCode: 'https://assets.dummyjson.com/public/qr-code.png',
      updatedAt: '2024-05-23T08:56:21.619Z',
    },
    minimumOrderQuantity: 8,
    price: 89.99,
    rating: 3.31,
    returnPolicy: '7 days return policy',
    reviews: [[Object], [Object], [Object]],
    shippingInformation: 'Ships in 2 weeks',
    sku: 'E70NB03B',
    stock: 91,
    tags: ['fragrances', 'perfumes'],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/thumbnail.png",
    title: "Dior J'adore",
    warrantyInformation: 'Lifetime warranty',
    weight: 10,
  },
];
